ALDER:
      _ALDER_default_:
                admixpop:        Non_Africans
                refpops:        Africans;Neandertals
                checkmap:        NO
                binsize:        0.00001
                mindis:        0.0001
                maxdis:        0.1
                fast_snp_read:        YES
                snp_outname:        YES
                num_threads:        4
      _ALDER_1_:
                binsize:        0.00001
                mindis:        0.00001
                maxdis:        0.1
