MASTER:
      _Default_Scenario_:
             alder: '_ALDER_1_'
             ascertainment: 0
             max_dist_Fit: 1
             Inferred_Demographies: [False,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
             Recombination_Map: [False,Recombination_Maps/Scaled_Genetic_AAMap.txt,No_correction]
             Complex_Demography: [False,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Scenario_1_:
             simulation: '_MS_fixed_Var_1_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_2_:
             simulation: '_MS_fixed_Var_2_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_3_:
             simulation: '_MS_fixed_Var_3_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_4_:
             simulation: '_MS_fixed_Var_4_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_5_:
             simulation: '_MS_fixed_Var_5_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_6_:
             simulation: '_MS_fixed_Var_6_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_7_:
             simulation: '_MS_fixed_Var_7_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_8_:
             simulation: '_MS_fixed_Var_8_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_9_:
             simulation: '_MS_fixed_Var_9_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_10_:
             simulation: '_MS_fixed_Var_10_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_11_:
             simulation: '_MS_fixed_mean_0_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_12_:
             simulation: '_MS_fixed_mean_1_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_13_:
             simulation: '_MS_fixed_mean_2_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_14_:
             simulation: '_MS_fixed_mean_3_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_15_:
             simulation: '_MS_fixed_mean_4_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_16_:
             simulation: '_MS_fixed_mean_5_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
      _Scenario_17_:
             simulation: '_MS_fixed_mean_0_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
      _Scenario_18_:
             simulation: '_MS_fixed_mean_5_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
      _Inferred_Demographies_Scenario_1_:
             simulation: '_MS_fixed_mean_0_Inf'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             Inferred_Demographies: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Inferred_Demographies_Scenario_2_:
             simulation: '_MS_fixed_mean_0_Inf'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
             Inferred_Demographies: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Inferred_Demographies_Scenario_3_:
             simulation: '_MS_fixed_mean_5_Inf'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             Inferred_Demographies: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Inferred_Demographies_Scenario_4_:
             simulation: '_MS_fixed_mean_5_Inf'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
             Inferred_Demographies: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Complex_Demographies_Scenario_1_:
             simulation: '_MS_fixed_mean_0_Complex'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             Complex_Demography: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Complex_Demographies_Scenario_2_:
             simulation: '_MS_fixed_mean_0_Complex'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
             Complex_Demography: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Complex_Demographies_Scenario_3_:
             simulation: '_MS_fixed_mean_5_Complex'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             Complex_Demography: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Complex_Demographies_Scenario_4_:
             simulation: '_MS_fixed_mean_5_Complex'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
             Complex_Demography: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Recombination_Map_Scenario_0_:
             simulation: '_MS_fixed_mean_0_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             Recombination_Map: [False,Recombination_Maps/Scaled_Genetic_AAMap.txt]
      _Recombination_Map_Scenario_1_:
             simulation: '_MS_fixed_mean_0_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
      _Recombination_Map_Scenario_2_:
             simulation: '_MS_fixed_mean_0_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
      _Recombination_Map_Scenario_3_:
             simulation: '_MS_fixed_mean_5_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
      _Recombination_Map_Scenario_4_:
             simulation: '_MS_fixed_mean_5_'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
      _Recombination_Map_and_Inferred_Demographies_Scenario_1_:
             simulation: '_MS_fixed_mean_0_Inf'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
             Inferred_Demographies: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Recombination_Map_and_Inferred_Demographies_Scenario_2_:
             simulation: '_MS_fixed_mean_0_Inf'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
             Inferred_Demographies: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Recombination_Map_and_Inferred_Demographies_Scenario_3_:
             simulation: '_MS_fixed_mean_5_Inf'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
             Inferred_Demographies: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Recombination_Map_and_Inferred_Demographies_Scenario_4_:
             simulation: '_MS_fixed_mean_5_Inf'
             min_dist_Fit: 0.02
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
             Inferred_Demographies: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Recombination_Map_and_Complex_Demographies_Scenario_1_:
             simulation: '_MS_fixed_mean_0_Complex'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
             Complex_Demography: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Recombination_Map_and_Complex_Demographies_Scenario_2_:
             simulation: '_MS_fixed_mean_0_Complex'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
             Complex_Demography: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Recombination_Map_and_Complex_Demographies_Scenario_3_:
             simulation: '_MS_fixed_mean_5_Complex'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
             Complex_Demography: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      _Recombination_Map_and_Complex_Demographies_Scenario_4_:
             simulation: '_MS_fixed_mean_5_Complex'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 1
             Recombination_Map: [True,Recombination_Maps/Scaled_Genetic_AAMap.txt]
             Complex_Demography: [True,Inferred_Pop_History/Vindjia_PSMC_inferred_Demography_unbiased_from_Mut_Rate_new.txt,Inferred_Pop_History/Yorubans_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt,Inferred_Pop_History/CEU_MSMC_inferred_Demography_unbiased_from_Mut_Rate.txt]
      Close_to_End_recent_GF_0:
             simulation: 'Close_to_End_Recent_GF_fixed_mean_0_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             max_dist_Fit: 10
             Recombination_Map: [False,Recombination_Maps/Scaled_HapMap.txt]
             Recombination_Correction: No_correction
      Close_to_End_recent_GF_1:
             simulation: 'Close_to_End_Recent_GF_fixed_mean_1_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             max_dist_Fit: 4
             Recombination_Map: [False,Recombination_Maps/Scaled_HapMap.txt]
             Recombination_Correction: No_correction
      Close_to_End_recent_GF_2:
             simulation: 'Close_to_End_Recent_GF_fixed_mean_2_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             max_dist_Fit: 3
             Recombination_Map: [False,Recombination_Maps/Scaled_HapMap.txt]
             Recombination_Correction: No_correction
      Close_to_End_recent_GF_3:
             simulation: 'Close_to_End_Recent_GF_fixed_mean_3_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             max_dist_Fit: 2
             Recombination_Map: [False,Recombination_Maps/Scaled_HapMap.txt]
             Recombination_Correction: No_correction
      Close_to_End_recent_GF_4:
             simulation: 'Close_to_End_Recent_GF_fixed_mean_4_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             max_dist_Fit: 1
             Recombination_Map: [False,Recombination_Maps/Scaled_HapMap.txt]
             Recombination_Correction: No_correction
      Close_to_End_recent_GF_5:
             simulation: 'Close_to_End_Recent_GF_fixed_mean_5_'
             min_dist_Fit: 0.05
             GF_Model: [GF_Model_IV,0]
             ascertainment: 0
             max_dist_Fit: 1
             Recombination_Map: [False,Recombination_Maps/Scaled_HapMap.txt]
             Recombination_Correction: No_correction
